image: node:20.2.0

cache:
  paths:
    - node_modules/

build:
  script:
    - npm ci
    - export NODE_ENV=production && npm run build

  cache:
    policy: push
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - mkdir public
    - mv dist/* public/
  cache:
    policy: pull
    paths:
      - node_modules/
  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
